language: php
php:
  - '5.6'
  - '7.0'

# 项目所在分支
branches:
  only:
  - master

services:
  - mysql
  - redis-server

# 配置环境
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `db_twinkle`;'

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: deploy
  keep-history: true
  on:
    branch: master
