language: php
php:
  - '5.6'
  - '7.0'

# 项目所在分支
branches:
  only:
  - master

services:
  - mysql
  - redis-server
  - memcached

# 配置环境
before_install:
  - phpenv config-add .travis/myconfig.ini
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `db_twinkle`;'

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

before_script:
  - mkdir -p Runtime
  - chmod 777 Runtime
  - php -m

script:
  - ./vendor/bin/phpunit --coverage-html=./Runtime/tests/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local_dir: Runtime/tests/
  keep-history: true
  on:
    branch: master
